language: node_js
node_js:
  - "4"

before_deploy: "[[ -z $BLUEMIX_PASS ]] && export BLUEMIX_PASS=$BLUEMIX_PASSWORD"

deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master
