language: node_js
node_js:
  - "4"

deploy:
    provider: bluemixcloudfoundry
    skip_cleanup: true
    manifest: manifest.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASS
    organization: $BLUEMIX_ORGANIZATION
    space: $BLUEMIX_SPACE
    on:
      branch: master
